'use client'

import { ArrowUpRight, CheckCircle, Zap, Shield, Coins, Globe } from 'lucide-react'
import { mdln, starknet, siteConfig } from '@/lib/site-config'
import { Stagger, StaggerItem } from '@medialane/ui'
import { AddressRow } from '@/components/address-row'
import { PageHero } from '@/components/page-hero'
import { StatCard } from '@/components/stat-card'
import { SectionHeader } from '@/components/section-header'

const tiers = [
  {
    num: '01',
    title: 'Observer',
    requirement: '1+ MDLN',
    description: 'Follow governance and join the community.',
    perks: ['View all proposals', 'Community forums', 'Discussions & feedback'],
    color: 'text-brand-purple',
  },
  {
    num: '02',
    title: 'Contributor',
    requirement: '100+ MDLN',
    description: 'Vote on proposals and shape the platform.',
    perks: ['Submit governance proposals', 'Vote on Snapshot', 'Early feature access', 'Contributor channels'],
    color: 'text-brand-blue',
  },
  {
    num: '03',
    title: 'Guardian',
    requirement: '1,000+ MDLN',
    description: 'Lead working groups and represent creators.',
    perks: ['Council nomination rights', 'Working group leadership', 'Ecosystem grants', 'Priority API access'],
    color: 'text-brand-purple',
  },
]

const starknetBenefits = [
  { icon: Zap,    color: 'bg-brand-purple/10 text-brand-purple', title: 'Fraction-of-cent fees',      body: 'Starknet transactions cost a fraction of Ethereum mainnet. Mint, list, and trade digital assets with near-zero gas.' },
  { icon: Shield, color: 'bg-brand-blue/10 text-brand-blue',     title: 'ZK-STARK security',          body: 'Every transaction batch is verified by STARK proofs on Ethereum. Cryptographic security without trusting a sequencer.' },
  { icon: Coins,  color: 'bg-brand-purple/10 text-brand-purple', title: 'Sponsored transactions',     body: 'Medialane sponsors gas for creator actions via native account abstraction. ' },
  { icon: Globe,  color: 'bg-brand-blue/10 text-brand-blue',     title: 'Native account abstraction', body: 'Wallets are smart contracts. Session keys (SNIP-9) enable PIN-authenticated gasless sessions across multiple actions.' },
]

export default function MembersPageClient() {
  return (
    <div className="px-4 sm:px-6 lg:px-10 xl:px-14 py-10 sm:py-12 lg:py-16 space-y-12">

      <PageHero
        eyebrow="Medialane · Membership"
        title="MDLN Token"
        description="21 million fixed supply. 100% DAO treasury. , , no preferential allocation.  Revenue generated by the protocol flows to the community treasury — MDLN holders vote annually on how it is used."
      />

      {/* Tokenomics stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard label="Total Supply" value="21,000,000" sub="MDLN · Fixed forever"   aurora="aurora-purple" />
        <StatCard label="DAO Treasury" value="100%"        sub="No external investors"  aurora="aurora-blue" auroraPos="-bottom-6 -right-6" />
        <StatCard label="Vesting"      value="9 years"     sub="Linear unlock schedule" aurora="aurora-purple" auroraPos="-top-6 -right-6" />
        <StatCard label="Voting Power" value="1:1"          sub="1 MDLN = 1 vote"        aurora="aurora-blue" auroraPos="-top-6 -left-6" />
      </div>

      {/* Distribution + Addresses */}
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="bento-cell p-5">
          <SectionHeader label="Token Distribution" />
          {[
            { label: 'Vesting (9 years)',  value: '18,900,000', pct: '90%', bar: 'w-[90%] bg-brand-purple' },
            { label: 'Operational runway', value: '2,100,000',  pct: '10%', bar: 'w-[10%] bg-brand-blue'   },
            { label: 'VC allocation',      value: '0',           pct: '0%',  bar: 'w-0'                      },
            { label: 'Team allocation',    value: '0',           pct: '0%',  bar: 'w-0'                      },
          ].map((row) => (
            <div key={row.label} className="py-2.5 border-b border-border/60 last:border-0">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-sm text-foreground">{row.label}</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono text-foreground/70">{row.value}</span>
                  <span className="text-[10px] font-mono text-muted-foreground/40 w-8 text-right">{row.pct}</span>
                </div>
              </div>
              <div className="h-1 w-full bg-muted rounded-full overflow-hidden">
                <div className={`h-full rounded-full ${row.bar}`} />
              </div>
            </div>
          ))}
        </div>

        <div className="bento-cell p-5">
          <SectionHeader label="On-chain Addresses · Ethereum" />
          <AddressRow label="Network"           value="Ethereum Mainnet" />
          <AddressRow label="Token Contract"    value={`${mdln.token.slice(0, 10)}…${mdln.token.slice(-6)}`}     href={mdln.etherscanToken}    />
          <AddressRow label="Vesting Contract"  value={`${mdln.vesting.slice(0, 10)}…${mdln.vesting.slice(-6)}`}  href={mdln.etherscanVesting}  />
          <AddressRow label="DAO Treasury"      value={`${mdln.treasury.slice(0, 10)}…${mdln.treasury.slice(-6)}`} href={mdln.etherscanTreasury} />
          <AddressRow label="Governance"        value="medialane.eth"     href={siteConfig.snapshot}            />
          <AddressRow label="MDLN on Starknet"  value={`${starknet.mdlnL2.slice(0, 10)}…${starknet.mdlnL2.slice(-6)}`} href={starknet.voyagerMdln} />
        </div>
      </div>

      {/* Bridge & Trade on Starknet */}
      <div>
        <SectionHeader label="Bridge & Trade on Starknet" color="text-brand-purple" bg="bg-brand-purple" className="mb-6" />
        <Stagger className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <StaggerItem>
            <a href={`https://starkgate.starknet.io/token/${starknet.mdlnL2}`} target="_blank" rel="noopener noreferrer"
              className="group flex flex-col gap-3 p-5 bento-cell hover:border-brand-purple/40 hover:shadow-sm transition-all duration-150 h-full">
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-semibold text-foreground group-hover:text-brand-purple transition-colors">Starkgate Bridge</p>
                <ArrowUpRight className="size-3.5 text-muted-foreground/20 group-hover:text-brand-purple transition-colors shrink-0" />
              </div>
              <p className="text-sm text-foreground leading-relaxed flex-1">Bridge MDLN from Ethereum mainnet to Starknet via the official Starkgate bridge. MDLN is live on Starknet — same token, two networks.</p>
              <div className="flex flex-wrap gap-1.5">
                {['Ethereum → Starknet', 'Live on Starknet', 'ERC-20'].map((t) => (
                  <span key={t} className="text-[10px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground/60 border border-border">{t}</span>
                ))}
              </div>
            </a>
          </StaggerItem>

          <StaggerItem>
            <a href="https://app.ekubo.org" target="_blank" rel="noopener noreferrer"
              className="group flex flex-col gap-3 p-5 bento-cell hover:border-brand-blue/40 hover:shadow-sm transition-all duration-150 h-full">
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-semibold text-foreground group-hover:text-brand-blue transition-colors">Ekubo Protocol</p>
                <ArrowUpRight className="size-3.5 text-muted-foreground/20 group-hover:text-brand-blue transition-colors shrink-0" />
              </div>
              <p className="text-sm text-foreground leading-relaxed flex-1">Trade MDLN on Starknet via Ekubo — Starknet&#39;s native concentrated liquidity AMM. MDLN/ETH and MDLN/USDC pools. Gasless swaps powered by account abstraction.</p>
              <div className="flex flex-wrap gap-1.5">
                {['AMM DEX', 'Starknet Native', 'Concentrated Liquidity'].map((t) => (
                  <span key={t} className="text-[10px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground/60 border border-border">{t}</span>
                ))}
              </div>
            </a>
          </StaggerItem>

          <StaggerItem>
            <div className="flex flex-col gap-3 p-5 bento-cell h-full">
              <p className="text-sm font-semibold text-foreground">Zero-fee Tokenization</p>
              <p className="text-sm text-foreground leading-relaxed flex-1">Minting digital assets on Medialane costs zero platform fees. Starknet transactions cost a fraction of a cent. Creator economy without extractive fees — 1% only on marketplace monetization.</p>
              <div className="flex flex-wrap gap-1.5">
                {['Free to Mint', '1% Marketplace Fee', 'Starknet L2'].map((t) => (
                  <span key={t} className="text-[10px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground/60 border border-border">{t}</span>
                ))}
              </div>
            </div>
          </StaggerItem>
        </Stagger>
      </div>

      {/* Starknet benefits */}
      <div>
        <SectionHeader label="Why Starknet" color="text-brand-blue" bg="bg-brand-blue" className="mb-6" />
        <Stagger className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {starknetBenefits.map(({ icon: Icon, color, title, body }) => (
            <StaggerItem key={title}>
              <div className="flex flex-col gap-3 p-5 bento-cell h-full">
                <div className={`flex size-9 items-center justify-center rounded-lg shrink-0 ${color}`}>
                  <Icon className="size-4" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground mb-1.5">{title}</p>
                  <p className="text-sm text-foreground leading-relaxed">{body}</p>
                </div>
              </div>
            </StaggerItem>
          ))}
        </Stagger>
      </div>

      {/* Membership tiers */}
      <div>
        <SectionHeader label="Membership Tiers" className="mb-6" />
        <Stagger className="grid sm:grid-cols-3 gap-4">
          {tiers.map((tier) => (
            <StaggerItem key={tier.title}>
              <div className="flex flex-col gap-4 p-5 bento-cell h-full">
                <div className="flex items-start justify-between">
                  <span className={`font-mono text-3xl font-black leading-none ${tier.color} opacity-80`}>
                    {tier.num}
                  </span>
                  <span className="text-[10px] font-mono text-muted-foreground/50 bg-muted px-2 py-1 rounded-full">{tier.requirement}</span>
                </div>
                <div>
                  <p className={`text-base font-bold ${tier.color}`}>{tier.title}</p>
                  <p className="text-sm text-foreground mt-1 leading-relaxed">{tier.description}</p>
                </div>
                <div className="h-px bg-border/60" />
                <ul className="space-y-2.5 flex-1">
                  {tier.perks.map((perk) => (
                    <li key={perk} className="flex items-start gap-2 text-sm text-foreground leading-relaxed">
                      <CheckCircle className="size-3.5 shrink-0 text-brand-purple mt-0.5" />
                      {perk}
                    </li>
                  ))}
                </ul>
              </div>
            </StaggerItem>
          ))}
        </Stagger>
      </div>

      {/* How to participate */}
      <div className="bento-cell p-6 sm:p-8">
        <SectionHeader label="How to Participate" className="mb-5" />
        <div className="grid sm:grid-cols-3 gap-6 mb-6">
          {[
            { step: '01', title: 'Acquire MDLN',  desc: 'Get MDLN on Ethereum via Uniswap, or trade directly on Starknet via Ekubo. Bridge between networks using StarkGate.' },
            { step: '02', title: 'Join Snapshot', desc: 'Connect to snapshot.org with your wallet holding MDLN to view and vote on proposals.' },
            { step: '03', title: 'Propose & Vote', desc: "Submit governance proposals, vote on platform decisions, and shape Medialane's future." },
          ].map((s) => (
            <div key={s.step} className="flex gap-3">
              <span className="font-mono text-xl font-black text-brand-purple/20 leading-none shrink-0">{s.step}</span>
              <div>
                <p className="text-sm font-bold text-foreground mb-1.5">{s.title}</p>
                <p className="text-sm text-foreground leading-relaxed">{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
        <div className="flex flex-wrap gap-3 pt-5 border-t border-border">
          <a href={siteConfig.snapshot} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-xl bg-brand-purple px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-purple/90 transition-colors">
            Vote on Snapshot <ArrowUpRight className="size-3.5" />
          </a>
          <a href={`https://starkgate.starknet.io/token/${starknet.mdlnL2}`} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-5 py-2.5 text-sm font-semibold text-foreground hover:bg-muted/50 transition-colors">
            Bridge via Starkgate <ArrowUpRight className="size-3.5" />
          </a>
          <a href="https://app.ekubo.org" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-5 py-2.5 text-sm font-semibold text-foreground hover:bg-muted/50 transition-colors">
            Trade on Ekubo <ArrowUpRight className="size-3.5" />
          </a>
          <a href={`https://app.uniswap.org/swap?outputCurrency=${mdln.token}`} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-5 py-2.5 text-sm font-semibold text-foreground hover:bg-muted/50 transition-colors">
            Buy on Uniswap <ArrowUpRight className="size-3.5" />
          </a>
        </div>
      </div>
    </div>
  )
}
